_format_version: "3.0"
_konnect:
  control_plane_name: serverless-default
consumers:
- keyauth_credentials:
  - id: 4c264e21-8e9b-4080-b745-625218446564
    key: api-test-key-2024
  tags:
  - managed-by-deck-api-test
  - generated-from-oas
  username: demo-user-api-test
services:
- host: 172.31.11.96
  id: 60c46456-5f9e-5b3d-8ef4-00b5d1be552e
  name: demo-api
  plugins: []
  port: 3000
  protocol: http
  routes:
  - id: 07143e93-1838-50b8-b4b3-93c6ae2ce65d
    methods:
    - GET
    name: demo-api_getitems
    paths:
    - ~/inquiry$
    plugins: []
    regex_priority: 200
    strip_path: false
    tags:
    - managed-by-deck-api-test
    - generated-from-oas
  - id: eb4706b0-2ece-536c-8539-8c5e417d987d
    methods:
    - GET
    name: demo-api_getitembyid
    paths:
    - ~/inquiry/(?<id>[^#?/]+)$
    plugins: []
    regex_priority: 100
    strip_path: false
    tags:
    - managed-by-deck-api-test
    - generated-from-oas
  - id: 415aafd5-9bba-5052-90fe-247196e0b596
    methods:
    - POST
    name: demo-api_order
    paths:
    - ~/order$
    plugins: []
    regex_priority: 200
    strip_path: false
    tags:
    - managed-by-deck-api-test
    - generated-from-oas
  tags:
  - managed-by-deck-api-test
  - generated-from-oas
  - team:api-test
upstreams: []
