patches:
  # Target CP
  - selectors:
      - $
    values:
      _konnect:
        control_plane_name: "serverless-default"

  # Add tags to all services
  - selectors:
      - $.services[*]
    values:
      tags:
        - managed-by-deck-api-test
        - generated-from-oas
        - team:api-test

  # Update target host, port, protocol for backend service
  - selectors:
      - $.services[?(@.name=="demo-api")]
    values:
      host: 172.31.11.96
      port: 3000
      protocol: http
    remove:
      - path
